# Generated by Django 4.1.7 on 2023-05-17 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['authorID']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['languageID']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['floor', 'shelf', 'row', 'bay']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['publisherID']},
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 7, 46, 11, 897834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bookrental',
            name='rentDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 7, 46, 11, 899833, tzinfo=datetime.timezone.utc)),
        ),
    ]
